#include "Hardware.hpp"
#include "Supervisor.hpp"
#include "GameWindow.hpp"
#include "i18n.hpp"
#include <algorithm>
#include <cmath>
#include "utils.hpp"
#include "compat/Compat.hpp"

// Provided for anyone who wants to recompile with new shaders without rerunning the premake script
#ifdef USE_C23_EMBED
static const char fragShaderBytes[] = {
#embed "ff.frag"
    , '\0'};

static const char vertShaderBytes[] = {
#embed "ff.vert"
    , '\0'};
#else
#include "autogenerated/Embeds.hpp"
#endif

constexpr u8 alphaThreshold = 4;

GfxInterface *Hardware::Init()
{
    Hardware* gfx = new Hardware;

    SDL_Init(SDL_INIT_VIDEO);
    u32 flags = WINDOW_FLAGS_COMPAT;

    if (g_Supervisor.cfg.windowed == 0)
    {
        flags |= SDL_FULLSCREEN_COMPAT;
    }

    g_GameWindow.CONFIGURE_INIT();
    #ifdef __ANDROID__
    GetWindowSize(&g_GameWindow.GAME_WINDOW_WIDTH_REAL,&g_GameWindow.GAME_WINDOW_HEIGHT_REAL);
    #endif
    g_GameWindow.CONFIGURE_VIEW();
    i32 width=g_GameWindow.GAME_WINDOW_WIDTH_REAL;
    i32 height=g_GameWindow.GAME_WINDOW_HEIGHT_REAL;
    i32 x = SDL_WINDOWPOS_UNDEFINED_COMPAT;
    i32 y = SDL_WINDOWPOS_UNDEFINED_COMPAT;

    gfx->window = SDL_CreateWindowCompat(TH_WINDOW_TITLE, x, y, width, height, flags);

    if (gfx->window == NULL)
    {
        delete gfx;
        return NULL;
    }

    //SDL 2 are on 3th variable... i'm trying SDL_RENDERER_SOFTWARE
    //SDL 3 are on 4th variable... i'm trying "direct3d12"
    //set 4th var into NULL to get the fastest SDL rendering
    gfx->renderer = SDL_CreateRendererCompat(
        gfx->window, 
        -1, 
        SDL_RENDERER_HARDWARE, 
        NULL
    );
    if (gfx->renderer == NULL)
    {
        delete gfx;
        return NULL;
    }

    gfx->device = SDL_CreateGPUDevice(
        SDL_GPU_SHADERFORMAT_SPIRV, // or DXIL/MSL depending on platform
        true,
        nullptr
    );

    if (!gfx->device)
    {
        delete gfx;
        return nullptr;
    }

    // only works on sdl3
    // SDL_PropertiesID props =
    //     SDL_GetRendererProperties(gfx->renderer);

    // const char* name =
    //     SDL_GetStringProperty(
    //         props,
    //         SDL_PROP_RENDERER_NAME_STRING,
    //         ""
    //     );

    // printf("Renderer: %s\n", name);

    gfx->model.Identity();
    gfx->view.Identity();
    gfx->projection.Identity();
    gfx->textureMatrix.Identity();

    SDL_Texture* framebufferTexture = SDL_CreateTexture(gfx->renderer, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING, g_GameWindow.GAME_WINDOW_WIDTH_REAL, g_GameWindow.GAME_WINDOW_HEIGHT_REAL);
    gfx->framebufferTexture = framebufferTexture;
    if (framebufferTexture == NULL)    {
        delete gfx;
        return NULL;
    }

    u32* framebuffer = new u32[g_GameWindow.GAME_WINDOW_WIDTH_REAL * g_GameWindow.GAME_WINDOW_HEIGHT_REAL];
    gfx->framebuffer = framebuffer;

    f32* depthBuffer = new f32[g_GameWindow.GAME_WINDOW_WIDTH_REAL * g_GameWindow.GAME_WINDOW_HEIGHT_REAL];
    gfx->depthBuffer = depthBuffer;

    SDL_GPUShaderCreateInfo vertInfo = {};
    vertInfo.code = (const Uint8*)vertShaderBytes;
    vertInfo.code_size = sizeof(vertShaderBytes) - 1;
    vertInfo.entrypoint = "main";
    vertInfo.format = SDL_GPU_SHADERFORMAT_SPIRV;
    vertInfo.stage = SDL_GPU_SHADERSTAGE_VERTEX;

    SDL_GPUShader* vertexShader = SDL_CreateGPUShader(
        gfx->device,
        &vertInfo);
    if (!vertexShader)
    {
        SDL_Log("Vertex shader error: %s", SDL_GetError());
    }

    gfx->info.vertex_shader = vertexShader;

    SDL_GPUShaderCreateInfo fragInfo = {};
    fragInfo.code = (const Uint8*)fragShaderBytes;
    fragInfo.code_size = sizeof(fragShaderBytes) - 1;
    fragInfo.entrypoint = "main";
    fragInfo.format = SDL_GPU_SHADERFORMAT_SPIRV;
    fragInfo.stage = SDL_GPU_SHADERSTAGE_FRAGMENT;

    SDL_GPUShader* fragmentShader = SDL_CreateGPUShader(
        gfx->device,
        &fragInfo);
    if (!fragmentShader)
    {
        SDL_Log("fragment shader error: %s", SDL_GetError());
    }

    gfx->info.fragment_shader = fragmentShader;

    gfx->info.primitive_type =
        SDL_GPU_PRIMITIVETYPE_TRIANGLELIST;

    gfx->info.rasterizer_state.fill_mode =
        SDL_GPU_FILLMODE_FILL;

    gfx->info.rasterizer_state.cull_mode =
        SDL_GPU_CULLMODE_NONE;

    gfx->info.multisample_state.sample_count =
        SDL_GPU_SAMPLECOUNT_1;

    gfx->info.depth_stencil_state.enable_depth_test = true;
    gfx->info.depth_stencil_state.enable_depth_write = true;
    gfx->info.depth_stencil_state.compare_op =
        SDL_GPU_COMPAREOP_LESS_OR_EQUAL;

    SDL_GPUColorTargetDescription colorTarget = {};
    // colorTarget.format = swapchainFormat;

    colorTarget.blend_state.enable_blend = true;
    colorTarget.blend_state.src_color_blendfactor =
        SDL_GPU_BLENDFACTOR_SRC_ALPHA;
    colorTarget.blend_state.dst_color_blendfactor =
        SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
    colorTarget.blend_state.color_blend_op =
        SDL_GPU_BLENDOP_ADD;

    gfx->info.target_info.num_color_targets = 1;
    gfx->info.target_info.color_target_descriptions =
        &colorTarget;

    gfx->info.target_info.depth_stencil_format =
        SDL_GPU_TEXTUREFORMAT_D24_UNORM;
            
    gfx->noVertexBuffer = g_Supervisor.cfg.opts & (1 << GCOS_DONT_USE_VERTEX_BUF);
    gfx->noFog = g_Supervisor.cfg.opts & (1 << GCOS_DONT_USE_FOG);

    gfx->cmd = SDL_AcquireGPUCommandBuffer(gfx->device);
    SDL_GPUTexture* swapchainTexture = nullptr;
    if (!SDL_WaitAndAcquireGPUSwapchainTexture(
        gfx->cmd,
        gfx->window,
        &swapchainTexture,
        nullptr,
        nullptr))
    {
        // return;
    }

    gfx->pipeline = SDL_CreateGPUGraphicsPipeline(
        gfx->device,
        &gfx->info);

    SDL_GPUSamplerCreateInfo samplerInfo = {};
    samplerInfo.min_filter = SDL_GPU_FILTER_LINEAR;
    samplerInfo.mag_filter = SDL_GPU_FILTER_LINEAR;
    samplerInfo.mipmap_mode = SDL_GPU_SAMPLERMIPMAPMODE_NEAREST;

    gfx->gpuSampler = SDL_CreateGPUSampler(
        gfx->device,
        &samplerInfo);

    SDL_GPUColorTargetInfo colorTarget2 = {};
    colorTarget2.texture = swapchainTexture;

    gfx->renderPass =
        SDL_BeginGPURenderPass(
            gfx->cmd,
            &colorTarget2,
            1,
            nullptr);
    utils::DebugPrint2("WARNING: Using software rasterizer, which can be slow. If performance is bad, make sure you're compiling with optimizations (building as release), or go with another graphics backend if possible.");

    return gfx;
}
bool Hardware::GameLoop(){
    SDL_Event e;

    while (SDL_PollEvent(&e))
    {
        if (e.type == SDL_QUIT)
        {
            return false;
        }
    }
    return true;
}


void Hardware::Exit()
{
    if (this->renderer)
    {
        SDL_DestroyRenderer(this->renderer);
        this->renderer = NULL;
    }
    if (this->window)
    {
        SDL_DestroyWindow(this->window);
        this->window = NULL;
    }
    if (this->framebufferTexture)
    {
        SDL_DestroyTexture(this->framebufferTexture);
        this->framebufferTexture = NULL;
    }
    if (this->framebuffer)    {
        delete[] this->framebuffer;
        this->framebuffer = NULL;
    }
    if (this->depthBuffer)
    {
        delete[] this->depthBuffer;
        this->depthBuffer = NULL;
    }
}

void Hardware::SetFogRange(f32 nearPlane, f32 farPlane)
{
    fogNear = nearPlane;
    fogFar = farPlane;
}

void Hardware::SetFogColor(ZunColor color)
{
    fogColor = color;
}

void Hardware::ToggleVertexAttribute(u8 attr, bool enable)
{
    if (attr & VERTEX_ATTR_TEX_COORD)
    {
        useTexCoord = enable;
    }
    if (attr & VERTEX_ATTR_DIFFUSE)
    {
        useDiffuse = enable;
    }
}

void Hardware::SetAttributePointer(VertexAttributeArrays attr, std::size_t stride, void *ptr)
{
    switch (attr)
    {
    case VERTEX_ARRAY_POSITION:
        this->vertexData = ptr;
        this->vertexStride = stride;
        break;
    case VERTEX_ARRAY_TEX_COORD:
        this->texCoordData = ptr;
        this->texCoordStride = stride;
        break;
    case VERTEX_ARRAY_DIFFUSE:
        this->diffuseData = ptr;
        this->diffuseStride = stride;
        break;
    }
}

void Hardware::SetColorOp(TextureOpComponent component, ColorOp op)
{

    if (component == COMPONENT_ALPHA)
    {
        return;
    }
    colorOp = op;
}

void Hardware::SetTextureFactor(ZunColor factor)
{
    textureFactor = factor;
}

void Hardware::SetTransformMatrix(TransformMatrix type, const ZunMatrix &matrix)
{
    switch (type) {
        case MATRIX_MODEL:
            model = matrix;
            break;
        case MATRIX_VIEW:
            view = matrix;
            break;
        case MATRIX_PROJECTION:
            projection = matrix;
            break;
        case MATRIX_TEXTURE:
            textureMatrix = matrix;
            break;
    }
}


void Hardware::Enable(Capabilities cap) {
    if(cap == CAPS_DEPTH_TEST) {
        useDepthTest = true;
    }
}

void Hardware::SetBlendMode(BlendMode mode) {
    blendMode = mode;
}

void Hardware::SetViewport(i32 x, i32 y, i32 width, i32 height) {
    viewport[0] = x;
    viewport[1] = y;
    viewport[2] = width;
    viewport[3] = height;
}

void Hardware::GetViewport(u32* viewport) {
    for (int i = 0; i < 4; i++) {
        viewport[i] = this->viewport[i];
    }
}

void Hardware::GetDepthRange(f32* depthRange) {
    depthRange[0] = this->depthNear;
    depthRange[1] = this->depthFar;
}


inline ZunColor RGBAToZunColor(u8 r, u8 g, u8 b, u8 a) {
    return ((ZunColor)a << 24) | ((ZunColor)r << 16) | ((ZunColor)g << 8) | (ZunColor)b;
}

inline ZunColor ColorDataToZunColor(ColorData colorData) {
    return RGBAToZunColor(colorData.r, colorData.g, colorData.b, colorData.a);
}

void Hardware::SetClearColor(f32 r, f32 g, f32 b, f32 a) {
    clearColor = RGBAToZunColor((u8)(r * 255), (u8)(g * 255), (u8)(b * 255), (u8)(a * 255));
}

void Hardware::SetTextureFilter() {
    SDL_SetHintCompat(SDL_HINT_RENDER_SCALE_QUALITY, "linear");
}

void Hardware::SetClearDepth(f32 depth) {
    clearDepth = depth;
}

void Hardware::Clear(u32 clearBits) {
    if (clearBits & CLEAR_COLOR_BUFFER) {
        std::fill(framebuffer, framebuffer + g_GameWindow.GAME_WINDOW_WIDTH_REAL * g_GameWindow.GAME_WINDOW_HEIGHT_REAL, clearColor);
    }
    if (clearBits & CLEAR_DEPTH_BUFFER) {
        std::fill(depthBuffer, depthBuffer + g_GameWindow.GAME_WINDOW_WIDTH_REAL * g_GameWindow.GAME_WINDOW_HEIGHT_REAL, clearDepth);
    }
}

void Hardware::SetDepthRange(f32 nearPlane, f32 farPlane) {
    depthNear = nearPlane;
    depthFar = farPlane;
}

void Hardware::SetDepthMask(bool enable) {
    depthMask = enable;
}

void Hardware::SetDepthFunc(DepthFunc func) {
    depthFunc = func;
}

GfxTextureHandle Hardware::CreateTexture()
{
    std::unique_ptr<GPUTexture> texture = std::unique_ptr<GPUTexture>(new GPUTexture());

    u32 id;
    if (!freeTextures.empty())
    {
        id = freeTextures.back();
        freeTextures.pop_back();
        textures[id] = std::move(texture);
    }
    else
    {
        id = textures.size();
        textures.push_back(std::move(texture));
    }

    return {id};
}

void Hardware::BindTexture(GfxTextureHandle handle)
{
    if (handle >= textures.size())
        return;
    if (!textures[handle.id])
        return;
    boundTexture = textures[handle.id].get();
}

void Hardware::DeleteTexture(GfxTextureHandle handle)
{
    if (handle.id >= textures.size())
        return;
    if (!textures[handle.id])
        return;
    textures[handle.id].reset();
    freeTextures.push_back(handle.id);
}

inline SDL_PIXEL_FORMAT_COMPAT GetSDLPixelFormat(PixelFormat fmt, PixelDataType type) {
    switch(type) {
        case PIXEL_UNSIGNED_BYTE:
            if(fmt == PIXEL_RGB) return SDL_PIXELFORMAT_RGB24;
            else return SDL_PIXELFORMAT_RGBA32;
        case PIXEL_UNSIGNED_SHORT_4_4_4_4:
            return SDL_PIXELFORMAT_RGBA4444;
        case PIXEL_UNSIGNED_SHORT_5_5_5_1:
            return SDL_PIXELFORMAT_RGBA5551;
        case PIXEL_UNSIGNED_SHORT_5_6_5:
            return SDL_PIXELFORMAT_RGB565;
    }
}

void Hardware::SetTextureImage(u32 width, u32 height, PixelFormat fmt, PixelDataType type, const void* data) {
    if (boundTexture) {
        SDL_GPUTextureCreateInfo texInfo = {};
        texInfo.type = SDL_GPU_TEXTURETYPE_2D;
        texInfo.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
        texInfo.width = width;
        texInfo.height = height;
        texInfo.layer_count_or_depth = 1;
        texInfo.num_levels = 1;
        texInfo.usage = SDL_GPU_TEXTUREUSAGE_SAMPLER;

        boundTexture->gpuTexture =
            SDL_CreateGPUTexture(device, &texInfo);
    }
}

void Hardware::SetTextureSubImage(
    i32 xoffset,
    i32 yoffset,
    i32 width,
    i32 height,
    const void* data)
{
    if (!boundTexture) return;
    //TODO : STUB
}

void Hardware::ReadPixels(i32 x, i32 y, i32 width, i32 height, const void* pixels) {
    u8* dst = (u8*)pixels;
    i32 pitch = width * 4;
    for (i32 row = 0; row < height; row++) {
        const u8* src = (u8*)framebuffer + ((g_GameWindow.GAME_WINDOW_HEIGHT_REAL - 1 - (y + row)) * g_GameWindow.GAME_WINDOW_WIDTH_REAL + x) * 4;
        memcpy(dst + row * pitch, src, pitch);
    }
}

void Hardware::Draw(
    PrimitiveType type,
    int start,
    int count)
{
    SDL_GPUBufferCreateInfo bufferInfo = {};
    bufferInfo.usage = SDL_GPU_BUFFERUSAGE_VERTEX;
    bufferInfo.size = count;

    vertexBuffer = SDL_CreateGPUBuffer(
        device,
        &bufferInfo);

    vertexBinding.buffer = vertexBuffer;
    
    SDL_BindGPUGraphicsPipeline(
        renderPass,
        pipeline);

    SDL_BindGPUVertexBuffers(
        renderPass,
        0,
        &vertexBinding,
        1);

    SDL_GPUTextureSamplerBinding samplerBinding = {};

    samplerBinding.texture = boundTexture->gpuTexture;

    samplerBinding.sampler =
        gpuSampler;

    SDL_BindGPUFragmentSamplers(
        renderPass,
        0,
        &samplerBinding,
        1);

    SDL_DrawGPUPrimitives(
        renderPass,
        count,
        1,
        start,
        0);
}

void Hardware::SwapBuffers()
{
    SDL_UpdateTexture(framebufferTexture, NULL, framebuffer, g_GameWindow.GAME_WINDOW_WIDTH_REAL * sizeof(u32));
    SDL_RenderCopy(renderer, framebufferTexture, NULL, NULL);
    SDL_RenderPresent(renderer);
}