#!/usr/bin/env python3
"""Generate GBK and Shift-JIS (CP932) to Unicode lookup tables as a C header.

Usage: python scripts/gen_encoding_tables.py [output_path]
Default output: src/encoding_tables.h
"""
import sys
import os


def gen_gbk_table():
    """GBK double-byte -> Unicode.
    Lead: 0x81-0xFE (126 values), Trail: 0x40-0xFE (191 values).
    Index = (lead - 0x81) * 191 + (trail - 0x40)
    """
    table = []
    for lead in range(0x81, 0xFF):
        for trail in range(0x40, 0xFF):
            try:
                ch = bytes([lead, trail]).decode("gbk")
                if len(ch) == 1:
                    table.append(ord(ch))
                else:
                    table.append(0)
            except (UnicodeDecodeError, ValueError):
                table.append(0)
    return table


def gen_sjis_double_table():
    """Shift-JIS (CP932) double-byte -> Unicode.
    Lead: 0x81-0x9F (31) + 0xE0-0xEF (16) = 47 values.
    Trail: 0x40-0xFC (189 values).
    Lead index = (lead <= 0x9F) ? (lead - 0x81) : (lead - 0xE0 + 31)
    Index = lead_index * 189 + (trail - 0x40)
    """
    leads = list(range(0x81, 0xA0)) + list(range(0xE0, 0xF0))
    table = []
    for lead in leads:
        for trail in range(0x40, 0xFD):
            try:
                ch = bytes([lead, trail]).decode("cp932")
                if len(ch) == 1:
                    table.append(ord(ch))
                else:
                    table.append(0)
            except (UnicodeDecodeError, ValueError):
                table.append(0)
    return table


def gen_sjis_kana_table():
    """Shift-JIS half-width katakana single-byte (0xA1-0xDF) -> Unicode."""
    table = []
    for b in range(0xA1, 0xE0):
        try:
            ch = bytes([b]).decode("cp932")
            table.append(ord(ch))
        except (UnicodeDecodeError, ValueError):
            table.append(0)
    return table


def format_table(name, table, cols=16):
    lines = [f"static const u16 {name}[{len(table)}] = {{"]
    for i in range(0, len(table), cols):
        row = table[i : i + cols]
        lines.append("    " + ",".join(f"0x{v:04X}" for v in row) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    outpath = sys.argv[1] if len(sys.argv) > 1 else os.path.join("src", "encoding_tables.h")

    print("Generating GBK table...")
    gbk = gen_gbk_table()
    gbk_nonzero = sum(1 for x in gbk if x)
    print(f"  {len(gbk)} entries, {gbk_nonzero} non-zero mappings")

    print("Generating Shift-JIS double-byte table...")
    sjis = gen_sjis_double_table()
    sjis_nonzero = sum(1 for x in sjis if x)
    print(f"  {len(sjis)} entries, {sjis_nonzero} non-zero mappings")

    print("Generating Shift-JIS kana table...")
    kana = gen_sjis_kana_table()
    print(f"  {len(kana)} entries")

    with open(outpath, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/gen_encoding_tables.py — DO NOT EDIT\n")
        f.write("// GBK and Shift-JIS (CP932) to Unicode lookup tables\n")
        f.write("#pragma once\n")
        f.write('#include "inttypes.hpp"\n\n')

        f.write("// GBK double-byte -> Unicode\n")
        f.write("// Index: (lead - 0x81) * 191 + (trail - 0x40)\n")
        f.write("// Lead: 0x81-0xFE, Trail: 0x40-0xFE\n")
        f.write(f"#define GBK_LEAD_MIN  0x81\n")
        f.write(f"#define GBK_LEAD_MAX  0xFE\n")
        f.write(f"#define GBK_TRAIL_MIN 0x40\n")
        f.write(f"#define GBK_TRAIL_MAX 0xFE\n")
        f.write(f"#define GBK_TRAIL_COUNT 191\n\n")
        f.write(format_table("g_gbkToUnicode", gbk))
        f.write("\n\n")

        f.write("// Shift-JIS (CP932) double-byte -> Unicode\n")
        f.write("// Lead index: (lead <= 0x9F) ? (lead - 0x81) : (lead - 0xE0 + 31)\n")
        f.write("// Trail: 0x40-0xFC\n")
        f.write(f"#define SJIS_LEAD1_MIN 0x81\n")
        f.write(f"#define SJIS_LEAD1_MAX 0x9F\n")
        f.write(f"#define SJIS_LEAD2_MIN 0xE0\n")
        f.write(f"#define SJIS_LEAD2_MAX 0xEF\n")
        f.write(f"#define SJIS_TRAIL_MIN 0x40\n")
        f.write(f"#define SJIS_TRAIL_MAX 0xFC\n")
        f.write(f"#define SJIS_TRAIL_COUNT 189\n\n")
        f.write(format_table("g_sjisToUnicode", sjis))
        f.write("\n\n")

        f.write("// Shift-JIS half-width katakana single-byte (0xA1-0xDF) -> Unicode\n")
        f.write(f"#define SJIS_KANA_MIN 0xA1\n")
        f.write(f"#define SJIS_KANA_MAX 0xDF\n\n")
        f.write(format_table("g_sjisKanaToUnicode", kana))
        f.write("\n")

    print(f"Written to {outpath}")


if __name__ == "__main__":
    main()
