@echo off

set DJGPP=E:\library\djgpp\djgpp.env
set GXX=E:\library\djgpp\bin\i586-pc-msdosdjgpp-g++.exe

if not exist build mkdir build

%GXX% ^
-DNO_SDL ^
-DUSE_DOS ^
-DGAME_WINDOW_DYNAMIC ^
-DGAME_WINDOW_SCALE ^
-DTH06_SOFTWARE_RENDER ^
-I../../src ^
-I../../build/autogenerated ^
-fpermissive ^
-O2 ^
-o build\th06.exe ^
../../src/main.cpp ^
../../src/AnmManager.cpp ^
../../src/AsciiManager.cpp ^
../../src/BombData.cpp ^
../../src/BulletData.cpp ^
../../src/BulletManager.cpp ^
../../src/Chain.cpp ^
../../src/EclManager.cpp ^
../../src/EffectManager.cpp ^
../../src/Ending.cpp ^
../../src/EnemyEclInstr.cpp ^
../../src/EnemyManager.cpp ^
../../src/FileSystem.cpp ^
../../src/GameErrorContext.cpp ^
../../src/GameManager.cpp ^
../../src/GamePaths.cpp ^
../../src/GameWindow.cpp ^
../../src/Gui.cpp ^
../../src/ItemManager.cpp ^
../../src/MainMenu.cpp ^
../../src/MusicRoom.cpp ^
../../src/Player.cpp ^
../../src/ReplayManager.cpp ^
../../src/ResultScreen.cpp ^
../../src/Rng.cpp ^
../../src/ScreenEffect.cpp ^
../../src/Stage.cpp ^
../../src/Supervisor.cpp ^
../../src/TextHelper.cpp ^
../../src/utils.cpp ^
../../src/ZunMath.cpp ^
../../src/ZunTimer.cpp ^
../../src/thirdparty/sjis_converter.cpp ^
../../src/midi/MidiDefault.cpp ^
../../src/graphics/Software2Ddos.cpp ^
../../src/pbg3/FileAbstraction.cpp ^
../../src/pbg3/IPbg3Parser.cpp ^
../../src/pbg3/Pbg3Archive.cpp ^
../../src/pbg3/Pbg3Parser.cpp ^
../../src/controller/DOSController.cpp ^
../../src/sound/EmptyMidiOutput.cpp ^
../../src/sound/EmptySoundPlayer.cpp

if errorlevel 1 goto :error

copy /Y ..\..\th06.ttf build\ >nul

echo.
echo SUCCESS
echo Output: build\th06.exe
goto :eof

:error
echo.
echo BUILD FAILED
exit /b 1